login/urls.py
from django.urls import path
from . import views, admin_views, manager_views, employee_views

app_name = 'App_Login'

urlpatterns = [
    path('signup/admin/', views.AdminSignUpView.as_view(), name='admin_signup'),
    path('signup/manager/', views.ManagerSignUpView.as_view(), name='manager_signup'),
    path('signup/employee/', views.EmployeeSignUpView.as_view(), name='employee_signup'),
    path('user_login/', views.user_login, name='user_login'),
    path('login/', views.login_page, name='login'),
    path('profile/admin/', admin_views.Profile.as_view(), name='admin_profile'),
    path('index/admin/', admin_views.index, name='index'),
    path('profile/manager/', manager_views.Profile.as_view(), name='manager_profile'),
    path('index/manager/', manager_views.index, name='manager_index'),
    path('profile/employee/', employee_views.EmployeeProfile.as_view(), name='employee_profile'),
    path('index/employee/', employee_views.index, name='employee_index'),
    path('employee_details/', admin_views.employee_view, name='employee'),
    path('manager_details/', admin_views.manager_view, name='manager'),
    path('logout/', views.logout_user, name='logout'),
    #admin dashboard
    path('home/', admin_views.admin_dashboard, name='admin_main_home'),
    #manager dashboard
    path('manager/home/', manager_views.manager_dashboard, name='manager_main_home'),
    #employee dashboard
    path('employee/home/', employee_views.employee_dashboard, name='employee_main_home'),
]

medicine/urls.py
from django.urls import path
from . import admin_views, manager_views, employee_views, views

app_name = 'medicine'

urlpatterns = [
    path('', views.main_home_page, name='main_home'),
    # admin urls
    path('admin/add_company/', admin_views.AddCompany.as_view(), name='add_company'),
    path('admin/view_company', admin_views.company_view, name='company_view'),
    path('admin/add_medicine/', admin_views.CreateMedicine.as_view(), name='admin_add_medicine'),
    path('admin/medicine_view', admin_views.medicine_view, name='admin_medicine_view'),
    path('admin/update/<pk>/', admin_views.UpdateMedicine.as_view(), name='admin_update_medicine'),
    path('admin/delete_medicine/<pk>/', admin_views.MedicineDelete.as_view(), name='admin_delete_medicine'),
    path('admin/search/', admin_views.search_medicine, name='admin_search_medicine'),
    path('admin/expire_date/', admin_views.search_medicine_expire_date, name='admin_view_expire_date'),
    path('admin/receipt', admin_views.receipt, name='admin_receipt'),
    path('admin/all_sales', admin_views.all_sales, name='admin_all_sales'),
    path('admin/receipt_detail/<int:receipt_id>/', admin_views.receipt_detail, name='admin_receipt_details'),
    path('admin/issue_item/<pk>/', admin_views.issue_item, name='admin_issue_item'),
    path('admin/add_to_stock/<pk>/', admin_views.add_to_stock, name='admin_add_to_stock'),
    path('admin/sell/product', admin_views.sell_product_detail, name='admin_sell_product'),
    path('update_company/<pk>/', admin_views.UpdateCompany.as_view(), name='admin_update_company'),
    path('delete_company/<pk>/', admin_views.CompanyDelete.as_view(), name='admin_delete_company'),
    path('search_company/', admin_views.search_company, name='admin_search_company'),

    # manager urls
    path('manger/add_company/', manager_views.AddCompany.as_view(), name='manager_add_company'),
    path('manager/view_company/', manager_views.company_view, name='manager_company_view'),
    path('manager/update_company/<pk>/', manager_views.UpdateCompany.as_view(), name='manager_update_company'),
    path('manager/delete_company/<pk>/', manager_views.CompanyDelete.as_view(), name='manager_delete_company'),
    path('manager/search_company/', manager_views.search_company, name='manager_search_company'),
    path('manager/medicine_view', manager_views.medicine_view, name='manager_medicine_view'),
    path('manager/add_medicine/', manager_views.CreateMedicine.as_view(), name='manager_add_medicine'),
    path('manager/update/<pk>/', manager_views.UpdateMedicine.as_view(), name='manager_update_medicine'),
    path('manager/delete_medicine/<pk>/', manager_views.MedicineDelete.as_view(), name='manager_delete_medicine'),
    path('manager/search/', manager_views.search_medicine, name='manager_search_medicine'),
    path('manager/expire_date/', manager_views.search_medicine_expire_date, name='manager_view_expire_date'),
    path('manager/receipt', manager_views.receipt, name='manager_receipt'),
    path('manager/all_sales', manager_views.all_sales, name='manager_all_sales'),
    path('manager/receipt_detail/<int:receipt_id>/', manager_views.receipt_detail, name='manager_receipt_details'),
    path('manager/issue_item/<pk>/', manager_views.issue_item, name='manager_issue_item'),
    path('manager/add_to_stock/<pk>/', manager_views.add_to_stock, name='manager_add_to_stock'),
    path('manager/sell/product', manager_views.sell_product_detail, name='manager_sell_product'),


    # employee urls
    path('employee/add_company/', employee_views.AddCompany.as_view(), name='employee_add_company'),
    path('employee/view_company/', employee_views.company_view, name='employee_company_view'),
    path('employee/update_company/<pk>/', employee_views.UpdateCompany.as_view(), name='employee_update_company'),
    path('employee/delete_company/<pk>/', employee_views.CompanyDelete.as_view(), name='employee_delete_company'),
    path('employee/search_company/', employee_views.search_company, name='employee_search_company'),
    path('employee/medicine_view', employee_views.medicine_view, name='employee_medicine_view'),
    path('employee/add_medicine/', employee_views.CreateMedicine.as_view(), name='employee_add_medicine'),
    path('employee/update/<pk>/', employee_views.UpdateMedicine.as_view(), name='employee_update_medicine'),
    path('employee/delete_medicine/<pk>/', employee_views.MedicineDelete.as_view(), name='employee_delete_medicine'),
    path('employee/search/', employee_views.search_medicine, name='employee_search_medicine'),
    path('employee/expire_date/', employee_views.search_medicine_expire_date, name='employee_view_expire_date'),
    path('employee/receipt', employee_views.receipt, name='employee_receipt'),
    path('employee/all_sales', employee_views.all_sales, name='employee_all_sales'),
    path('employee/receipt_detail/<int:receipt_id>/', employee_views.receipt_detail, name='employee_receipt_details'),
    path('employee/issue_item/<pk>/', employee_views.issue_item, name='employee_issue_item'),
    path('employee/add_to_stock/<pk>/', employee_views.add_to_stock, name='employee_add_to_stock'),
    path('employee/sell/product', employee_views.sell_product_detail, name='employee_sell_product'),

]

new_medicla_store_inventory_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('medicine.urls')),
     path('account/', include('login.urls')),
]
urlpatterns += staticfiles_urlpatterns()

templates/Employee/HomePage.html
{% load static %}
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <span class="brand-text font-weight-light">Medical Store Inventory System</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="info">
          <a href="#" class="d-block">{{ user.s_name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            {% url 'App_Login:employee_main_home' as employee_home %}
            <a href="{{ employee_home }}" class="nav-link {% if request.path == employee_home %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Home
              </p>
            </a>
          </li>


          <li class="nav-item">
            {% url 'App_Login:employee_profile' as profile %}
            <a href="{{ profile }}" class="nav-link {% if request.path == profile %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                My Profile
              </p>
            </a>
          </li>

          <li class="nav-item">
              {% url 'medicine:employee_add_company' as add_company %}
            <a href="{{ add_company }}" class="nav-link {% if request.path == add_company %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Add Company Information
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'medicine:employee_company_view' as view_company %}
            <a href="{{ view_company }}" class="nav-link {% if request.path == view_company %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Company Information Details
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'medicine:employee_search_company' as admin_search_company %}
             <a href="{{ admin_search_company }}" class="nav-link {% if request.path == admin_search_company %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Search Company Details
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'medicine:employee_add_medicine' as add_medicine %}
            <a href="{{ add_medicine }}" class="nav-link {% if request.path == add_medicine %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Add Medicine
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'medicine:employee_medicine_view' as Medicine_View %}
            <a href="{{ Medicine_View }}" class="nav-link {% if request.path == Medicine_View %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                 Medicine View
              </p>
            </a>
          </li>
           <li class="nav-item">
             {% url 'medicine:employee_search_medicine' as search_medicine %}
            <a href="{{ search_medicine }}" class="nav-link {% if request.path == search_medicine %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Search Medicine
              </p>
            </a>
          </li>
           <li class="nav-item">
               {% url 'medicine:employee_view_expire_date' as expire_date_medicine %}
            <a href="{{ expire_date_medicine }}" class="nav-link {% if request.path == expire_date_medicine %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Expire Date Medicine
              </p>
            </a>
          </li>
         <li class="nav-item">
                 {% url 'medicine:employee_sell_product' as sales_item %}
            <a href="{{ sales_item }}" class="nav-link {% if request.path == sales_item %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Sales Item
              </p>
            </a>
          </li>

           <li class="nav-item">
               {% url 'medicine:employee_receipt' as Receipt %}
            <a href="{{ Receipt }}" class="nav-link {% if request.path == Receipt %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Receipt
              </p>
            </a>
          </li>
            <li class="nav-item">
                 {% url 'medicine:employee_all_sales' as sales_receipt %}
            <a href="{{ sales_receipt }}" class="nav-link {% if request.path == sales_receipt %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Sales Report
              </p>
            </a>
          </li>


        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

templates/Employee/employee_home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <a href="{% url 'App_Login:employee_profile' %}"><h2>Profile</h2></a>
<a href="{% url 'medicine:employee_add_company' %}"><h2>Add Company</h2></a>
<a href="{% url 'medicine:employee_company_view' %}"><h2>View Company</h2></a>
<a href="{% url 'medicine:employee_search_company' %}" ><h2>Search view</h2></a>
<a href="{% url 'medicine:employee_medicine_view' %}"><h2>Medicine View</h2></a>
<a href="{% url 'medicine:employee_add_medicine' %}"><h2>Add Medicine</h2></a>
<a href="{% url 'medicine:employee_search_medicine' %}"><h2>Search Medicine</h2></a>
 <a href="{% url 'medicine:employee_view_expire_date' %}"><h2>Expire Date of Medicine</h2></a>
<a href="{% url 'App_Login:logout' %}"><h2>Logout</h2></a>
</body>
</html>

templates/Employee/employee_main_homepage.html
{% extends 'new.html' %}
{% block main_content %}
    <section class="content">
      <div class="container-fluid">
          <div class="row">

          <!-- ./col -->

          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>{{ medicine_count }}</h3>

                <p>Total Medicines</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="{% url 'medicine:manager_medicine_view' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>{{ company_count }}</h3>

                <p>Total Company</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="{% url 'medicine:manager_company_view' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
        </div>
              <div class="col-lg-6">
                   <div class="card card-success">
                  <div class="card-header">
                    <h3 class="card-title">Total Medicine in Each Company</h3>

                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                      </button>
                      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                  </div>
                  <div class="card-body">
                    <canvas id="donutChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                  </div>
                  <!-- /.card-body -->
                </div>
              </div>
          </div>

                  <!-- /.card-body -->
                </div>
              </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

templates/Employee/product_detail.html
{% extends 'new.html' %}
{% load crispy_forms_tags %}
{% block main_content %}
<center>
<div class = "container">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Item Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Expire Date</th>
        <th scope="col">Buy Item</th>
        <th scope="col">Received of Items </th>
      </tr>
    </thead>
    <tbody>
     {% for product in product_list  %}
          <tr>
            <td>{{ product.name }}</td>
            <td>{{ product.total_quantity }}</td>
            <td>{{ product.unit_price }}</td>
            <td>{{ product.expire_date }}</td>
            <td><a href="{% url 'medicine:employee_issue_item' pk=product.pk %}" ><input type="submit" value="Buy Item" class="btn btn-secondary" btn type="button"/></a></td>
            <td><a href="{% url 'medicine:employee_add_to_stock' pk=product.pk %}" ><input type= "submit" value="Received of Items" class="btn btn-secondary btn" type="button"/></a></td>
          </tr>
     {% endfor %}
    </tbody>
  </table>
</div>
</center>
{% endblock main_content %}

templates/Employee/profile.html
{% extends 'new.html' %}
{% load crispy_forms_tags %}
{% block main_content %}
<center>
<div class="container">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Complete Your Details</h5>
        <form method="POST" enctype="multipart/form-data">
              {{ form|crispy }}
              {% csrf_token %}
         <button type="submit" class="btn btn-success btn-sm">Save</button>
      </form>
      </div>
    </div>
  </div>
</center>
{% endblock main_content %}